### ISSUE TITLE
"Basics of Congruence" page not loading

### ISSUE THREAD

**Issue by ShivamVashishtha** [0shaurya/mathular#1]
<img width="1047" alt="Screen Shot 2022-06-27 at 8 18 36 PM" src="https://user-images.githubusercontent.com/58797316/176066248-04335fda-eb50-42ac-bf99-64c16975887b.png">

The page isn't loading despite the file name **(Basics of Congruence)** being corrected on every **index.html** page in every folder.

**Comment by 0shaurya** [comment]
nav.js is updated, should be fixed.
